### ISSUE TITLE
docker GPU 中文离线版本识别BUG-有部分音频推理报错

### ISSUE THREAD

**Issue by chenpaopao** [modelscope/FunASR#2435]
Notice: In order to resolve issues more efficiently, please raise issue following the template.
（注意：为了更加高效率解决您遇到的问题，请按照模板提问，补充细节）

### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

1. Run cmd '....'
启动离线版本GPU docker：funasr-runtime-sdk-gpu-0.2.0 (d280bf7e495b)
cd $cmd_path
$cmd_path/${cmd}  \
  --download-model-dir "${download_model_dir}" \
  --model-dir "${model_dir}" \
  --vad-dir "${vad_dir}" \
  --punc-dir "${punc_dir}" \
  --itn-dir "${itn_dir}" \
  --lm-dir "${lm_dir}" \
  --decoder-thread-num ${decoder_thread_num} \
  --model-thread-num ${model_thread_num} \
  --io-thread-num  ${io_thread_num} \
  --port ${port} \
  --certfile  "${certfile}" \
  --keyfile "${keyfile}" \
  --hotword "${hotword}" \
  --bladedisc "${bladedisc}" \
  --batch-size "${batch_size}" \
  --gpu &
3. See error
当上传音频文件推理时候，有一些音频文件上传后，会出现如下错误信息：
E20250317 12:47:16.232656 164614 paraformer-torch.cpp:471] The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/funasr/models/bicif_paraformer/model.py", line 31, in forward
    _3 = torch.slice(_2, 0, 0, 9223372036854775807)
    mask = torch.slice(torch.unsqueeze(_3, 1), 2, 0, 9223372036854775807)
    _4, _5, = (predictor2).forward(_1, mask, )
               ~~~~~~~~~~~~~~~~~~~ <--- HERE
    lengths = torch.to(torch.round(_4), 3)
    _6 = (decoder).forward(lengths, speech_lengths, _5, _1, )
  File "code/__torch__/funasr/models/bicif_paraformer/cif_predictor.py", line 44, in forward
    alphas4 = torch.add(alphas3, tail_threshold)
    _5 = torch.zeros([_2, 1, _4], dtype=6, layout=None, device=torch.device("cpu"), pin_memory=False)
    zeros = torch.to(_5, dtype=6, layout=0, device=torch.device("cuda:0"))
            ~~~~~~~~ <--- HERE
    hidden = torch.cat([argument_1, zeros], 1)
    token_num = torch.sum(alphas4, [-1])

Traceback of TorchScript, original code (most recent call last):
/home/liangxianchen/lxc-llm/miniconda3/envs/python3_10/lib/python3.10/site-packages/funasr/models/bicif_paraformer/cif_predictor.py(459): tail_process_fn
/home/liangxianchen/lxc-llm/miniconda3/envs/python3_10/lib/python3.10/site-packages/funasr/models/bicif_paraformer/cif_predictor.py(414): forward
/home/liangxianchen/lxc-llm/miniconda3/envs/python3_10/lib/python3.10/site-packages/torch/nn/modules/module.py(1522): _slow_forward
/home/liangxianchen/lxc-llm/miniconda3/envs/python3_10/lib/python3.10/site-packages/torch/nn/modules/module.py(1541): _call_impl
/home/liangxianchen/lxc-llm/miniconda3/envs/python3_10/lib/python3.10/site-packages/torch/nn/modules/module.py(1532): _wrapped_call_impl
/home/liangxianchen/lxc-llm/miniconda3/envs/python3_10/lib/python3.10/site-packages/funasr/models/bicif_paraformer/export_meta.py(48): export_forward
/home/liangxianchen/lxc-llm/miniconda3/envs/python3_10/lib/python3.10/site-packages/torch/nn/modules/module.py(1522): _slow_forward
/home/liangxianchen/lxc-llm/miniconda3/envs/python3_10/lib/python3.10/site-packages/torch/nn/modules/module.py(1541): _call_impl
/home/liangxianchen/lxc-llm/miniconda3/envs/python3_10/lib/python3.10/site-packages/torch/nn/modules/module.py(1532): _wrapped_call_impl
/home/liangxianchen/lxc-llm/miniconda3/envs/python3_10/lib/python3.10/site-packages/torch/jit/_trace.py(1088): trace_module
/home/liangxianchen/lxc-llm/miniconda3/envs/python3_10/lib/python3.10/site-packages/torch/jit/_trace.py(820): trace
/home/liangxianchen/lxc-llm/miniconda3/envs/python3_10/lib/python3.10/site-packages/funasr/utils/export_utils.py(129): _torchscripts
/home/liangxianchen/lxc-llm/miniconda3/envs/python3_10/lib/python3.10/site-packages/funasr/utils/export_utils.py(33): export
/home/liangxianchen/lxc-llm/miniconda3/envs/python3_10/lib/python3.10/site-packages/funasr/auto/auto_model.py(664): export
/home/liangxianchen/lxc-data/FunASR/examples/industrial_data_pretraining/paraformer/export.py(16): <module>
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
<!-- If you have a code sample, error messages, stack traces, please provide it here as well -->


#### Code sample
<!-- Ideally attach a minimal code sample to reproduce the decried issue.
Minimal means having the shortest code but still preserving the bug. -->


### Expected behavior

<!-- A clear and concise description of what you expected to happen. -->

### Environment

 - OS (e.g., Linux):
 - FunASR Version (e.g., 1.0.0):
 - ModelScope Version (e.g., 1.11.0):
 - PyTorch Version (e.g., 2.0.0):
 - How you installed funasr (`pip`, source):
 - Python version:
 - GPU (e.g., V100M32)
 - CUDA/cuDNN version (e.g., cuda11.7):
 - Docker version (e.g., funasr-runtime-sdk-cpu-0.4.1)
 - Any other relevant information:

### Additional context

<!-- Add any other context about the problem here. -->

**Comment by chenpaopao** [comment]
已解决，可能是我在本地T4GPU导出的模型，而测试时用的K80gou

**Comment by lukeewin** [comment]
> 已解决，可能是我在本地T4GPU导出的模型，而测试时用的K80gou

你好，请问你是如何解决的？我也报一样的错误，如下所示：
```shell
CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```
似乎是cuda内核访问错误。请问你是如何解决的？
