### ISSUE TITLE
GPU版本镜像不介绍CUDA是多少的？

### ISSUE THREAD

**Issue by v-49** [modelscope/FunASR#2553]
不论是：[https://cr.console.aliyun.com/repository/cn-hangzhou/funasr_repo/funasr/images](https://www.google.com/url?sa=E&q=https%3A%2F%2Fcr.console.aliyun.com%2Frepository%2Fcn-hangzhou%2Ffunasr_repo%2Ffunasr%2Fimages)仓库中的都没有介绍对应的CUDA 
0.2.0版本是使用CUDA 11.3  和我的12.4不兼容无法使用 也没有在发布内容上提到cuda条件

File "/workspace/FunASR/funasr/download/runtime_sdk_download_tool.py", line 58, in <module>
main()
File "/workspace/FunASR/funasr/download/runtime_sdk_download_tool.py", line 50, in main
export_model = AutoModel(model=args.model_name, output_dir=output_dir, device=args.device)
File "/workspace/FunASR/funasr/auto/auto_model.py", line 125, in init
model, kwargs = self.build_model(**kwargs)
File "/workspace/FunASR/funasr/auto/auto_model.py", line 284, in build_model
model.to(device)
File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 927, in to
return self._apply(convert)
File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 579, in _apply
module._apply(fn)
File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 579, in _apply
module._apply(fn)
File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/rnn.py", line 189, in _apply
self.flatten_parameters()
File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/rnn.py", line 175, in flatten_parameters
torch._cudnn_rnn_flatten_weight(
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
I20250617 07:50:21.940557   277 funasr-wss-server.cpp:308] Failed to download model from modelscope. If you set local asr model path, you can ignore the errors.
E20250617 07:50:21.940707   277 funasr-wss-server.cpp:312] /workspace/models/damo/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch/model_blade.torchscript do not exists.

**Comment by v-49** [comment]
> 手头是5090系列的显卡吗

H20

**Comment by GanziPo** [comment]
请问解决了吗? 5090遇到同样的问题

**Comment by v-49** [comment]
> 请问解决了吗? 5090遇到同样的问题

没有 最后用的CPU版本 部署了4个服务每个服务10个线程做动态分配处理

**Comment by bageluse** [comment]
我这里解决了，显卡是5090D。不过我是源码编译的。py3.10。 cuda_12.8  ，ubuntu24.04   torch 2.7.1 . 我是这样配置没问题

**Comment by bageluse** [comment]
https://github.com/modelscope/FunASR/blob/main/README_zh.md  就是根据这个文档源码编译的

**Comment by lukeewin** [comment]
> 我这里解决了，显卡是5090D。不过我是源码编译的。py3.10。 cuda_12.8 ，ubuntu24.04 torch 2.7.1 . 我是这样配置没问题

你好你不用安装torch_blade吗？
